imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

editor:
    config:
        contentsCss: "EXT:sand_sitepackage/Resources/Public/Css/rte.css"

        stylesSet:
            - { name: "text color blue", element: "p", attributes: { 'class': 'text-color-blue' } }
            - { name: "text-center", element: "p", attributes: { 'class': 'content-paragraph mt-5 text-center' } }
            - { name: "content-paragraph", element: "p", attributes: { 'class': 'content-paragraph' } }
            - { name: "text-color-blue mt-3 max-w-[980px]", element: "p", attributes: { 'class': 'content-paragraph text-color-blue mt-3 max-w-[980px]' } }
            - { name: "text-color-blue", element: "p", attributes: { 'class': 'content-paragraph text-color-blue' } }
            - { name: "blue text mt5", element: "p", attributes: { 'class': 'content-paragraph mt-5 text-color-blue' } }
            - { name: "list square-white", element: "p", attributes: { 'class': 'list-style-square-white' } }
            - { name: "list square-blue", element: "p", attributes: { 'class': 'list-style-square-blue' } }
            - { name: "list square-black", element: "p", attributes: { 'class': 'list-style-square-black' } }
            - { name: "list circle-white", element: "p", attributes: { 'class': 'list-style-circle-white' } }
            - { name: "list circle-blue", element: "p", attributes: { 'class': 'list-style-circle-blue' } }
            - { name: "list circle-black", element: "p", attributes: { 'class': 'list-style-circle-black' } }
            - { name: "list circle-trugreen", element: "p", attributes: { 'class': 'list-style-circle-trugreen' } }
         
            
            - { name: "absolute left", element: "div", attributes: { 'class': 'content-template-2 lg:absolute left-0 top-2/4 lg:-translate-y-2/4' } }
            - { name: "content-bordered-y", element: "div", attributes: { 'class': 'content-bordered-y' } }
            - { name: "div", element: "div", attributes: { 'class': ' ' } }
            - { name: "left blue text", element: "div", attributes: { 'class': 'content-paragraph mt-5' } }
            - { name: "bordered text", element: "div", attributes: { 'class': 'content-bordered-y mt-12' } }
            - { name: "px-10", element: "div", attributes: { 'class': 'content-paragraph mt-0 py-4 px-10' } }

            - { name: "span", element: "span", attributes: { 'class': ' ' } }
            - { name: "blue bold font", element: "span", attributes: { 'class': 'content-title mt-0 text-color-blue text-7xl DINpro-bold font-bold' } }
            - { name: "blue font", element: "span", attributes: { 'class': 'content-title mt-0 text-color-blue mb-6' } }
            - { name: "buttom text", element: "span", attributes: { 'class': 'txt bottom' } }
            - { name: "blue-square", element: "span", attributes: { 'class': 'blue-square square-list' } }
       
            - { name: "white with blue hover", element: "a", attributes: { 'class': 'btn-blue-outlined' } }
            - { name: "white with black hover", element: "a", attributes: { 'class': 'btn-black-outlined' } }
            - { name: "white with trugreen hover", element: "a", attributes: { 'class': 'btn-trugreen-outlined' } }
            - { name: "blue button", element: "a", attributes: { 'class': 'btn-blue' } }
            - { name: "black button", element: "a", attributes: { 'class': 'btn-black' } }
            - { name: "trugreen button", element: "a", attributes: { 'class': 'btn-trugreen' } }

            - { name: "square li", element: "li", attributes: { 'class': 'content-paragraph mt-2 list-style-square-white' } }
            - { name: "normal li", element: "li", attributes: { 'class': 'content-paragraph mt-2 list-style-square-transparent' } }
            - { name: "default li", element: "li", attributes: { 'class': ' ' } }

            - { name: "title", element: "h1", attributes: { 'class': 'title' } }
            - { name: "title underline", element: "h1", attributes: { 'class': 'title-underline' } }
            - { name: "title rectangle", element: "h1", attributes: { 'class': 'title-rectangle' } }
            - { name: "title rectangle underline", element: "h1", attributes: { 'class': 'title-rectangle-w-underline' } }

            - { name: "h2", element: "h2", attributes: { 'class': ' ' } }
            - { name: "h2 with buttom border", element: "h2", attributes: { 'class': 'content-title border-bottom' } }

            - { name: "h3 color-blue", element: "h3", attributes: { 'class': 'content-title text-color-blue' } }
            - { name: "h3 white", element: "h3", attributes: { 'class': 'content-title' } }

            - { name: "strong", element: "strong", attributes: { 'class': ' ' } }


            





        toolbarGroups:
            - { name: styles, groups: [ format, styles ] }
            - { name: basicstyles, groups: [ basicstyles ] }
            - { name: paragraph, groups: [ list, indent, blocks, align ] }
            - "/"
            - { name: links, groups: [ links ] }
            - { name: clipboard, groups: [ clipboard, cleanup, undo ] }
            - { name: editing, groups: [ spellchecker ] }
            - { name: insert, groups: [ insert ] }
            - { name: tools, groups: [ table, specialchar ] }
            - { name: document, groups: [ mode ] }

        format_tags: "p;h1;h2;h3;h4;pre"

        justifyClasses:
            - text-left
            - text-center
            - text-right
            - text-justify

        extraPlugins:
            - justify

        removePlugins:
            - image

        removeButtons:
            - Anchor
            - Underline
            - Strike
            
        extraAllowedContent:
            - img[!src,alt,width,height]